name: quickjs
description: A dart binding of quickjs, a powerful js engine with native_assets_cli.
version: 1.1.0-dev.1
repository: https://github.com/lindeer/quickjs-dart

topics:
  - js

environment:
  sdk: ^3.10.1

dependencies:
  code_assets: ^1.0.0
  hooks: ^1.0.0
  ffi: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.24.0
